In [2]:
import os
import copy
import numpy as np
import pandas as pd
import geopandas as gpd

from pathlib import Path

from src import utils

import seaborn as sns
import matplotlib.pyplot as plt
sns.set_context("paper", font_scale=1.25)

from src.data.lfs import EulfsDs

%load_ext autoreload
%autoreload 2

In [7]:
gdf1 = gpd.read_file(r"T:\Documents\Projects\04_jrc_green-skills-regional\03_data"
                    r"-analysis\re4gt\data\external\geodata\NUTS_RG_03M_2021_4326.shp")

In [12]:
nuts_lvl = 2
gdf1.loc[gdf1["LEVL_CODE"] == nuts_lvl]

,NUTS_ID,LEVL_CODE,CNTR_CODE,NAME_LATN,NUTS_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,FID,geometry
86,AL01,2,AL,Veri,Veri,0.0,NaN,0,AL01,"POLYGON ((19.83100 42.46645, 19.84072 42.47881..."
87,AL02,2,AL,Qender,Qender,0.0,NaN,0,AL02,"POLYGON ((20.23617 41.34849, 20.29263 41.37277..."
89,DE24,2,DE,Oberfranken,Oberfranken,0.0,NaN,0,DE24,"POLYGON ((11.48157 50.43162, 11.48290 50.40161..."
103,IE05,2,IE,Southern,Southern,0.0,NaN,0,IE05,"MULTIPOLYGON (((-7.67408 52.78129, -7.61737 52..."
109,HU11,2,HU,Budapest,Budapest,0.0,NaN,0,HU11,"POLYGON ((18.93274 47.57117, 19.02713 47.58717..."
...,...,...,...,...,...,...,...,...,...,...
1543,NO02,2,NO,Innlandet,Innlandet,0.0,NaN,0,NO02,"POLYGON ((8.25170 61.07394, 8.13528 61.11635, ..."
1598,NO06,2,NO,Trøndelag,Trøndelag,0.0,NaN,0,NO06,"MULTIPOLYGON (((14.32598 65.11892, 14.27336 65..."
1599,NO07,2,NO,Nord-Norge,Nord-Norge,0.0,NaN,0,NO07,"MULTIPOLYGON (((31.14892 70.39862, 31.14905 70..."
1728,NO08,2,NO,Oslo og Viken,Oslo og Viken,0.0,0.0,0,NO08,"MULTIPOLYGON (((11.84559 59.84296, 11.92697 59..."
1938,LT02,2,LT,Vidurio ir vakarų Lietuvos regionas,Vidurio ir vakarų Lietuvos regionas,0.0,NaN,0,LT02,"POLYGON ((25.82139 56.05218, 25.85250 56.02579..."

In [8]:
gdf2 = gpd.read_file(r"T:\Documents\Projects\04_jrc_green-skills-regional\03_data"
                     r"-analysis\re4gt\data\external\geodata\NUTS_RG_03M_2021_4326_LEVL_2")

In [9]:
gdf2

,NUTS_ID,LEVL_CODE,CNTR_CODE,NAME_LATN,NUTS_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,FID,geometry
0,AL01,2,AL,Veri,Veri,0.0,NaN,0,AL01,"POLYGON ((19.83100 42.46645, 19.84072 42.47881..."
1,AL02,2,AL,Qender,Qender,0.0,NaN,0,AL02,"POLYGON ((20.23617 41.34849, 20.29263 41.37277..."
2,DE24,2,DE,Oberfranken,Oberfranken,0.0,NaN,0,DE24,"POLYGON ((11.48157 50.43162, 11.48290 50.40161..."
3,IE05,2,IE,Southern,Southern,0.0,NaN,0,IE05,"MULTIPOLYGON (((-7.67408 52.78129, -7.61737 52..."
4,HU11,2,HU,Budapest,Budapest,0.0,NaN,0,HU11,"POLYGON ((18.93274 47.57117, 19.02713 47.58717..."
...,...,...,...,...,...,...,...,...,...,...
329,NO02,2,NO,Innlandet,Innlandet,0.0,NaN,0,NO02,"POLYGON ((8.25170 61.07394, 8.13528 61.11635, ..."
330,NO06,2,NO,Trøndelag,Trøndelag,0.0,NaN,0,NO06,"MULTIPOLYGON (((14.32598 65.11892, 14.27336 65..."
331,NO07,2,NO,Nord-Norge,Nord-Norge,0.0,NaN,0,NO07,"MULTIPOLYGON (((31.14892 70.39862, 31.14905 70..."
332,NO08,2,NO,Oslo og Viken,Oslo og Viken,0.0,0.0,0,NO08,"MULTIPOLYGON (((11.84559 59.84296, 11.92697 59..."
333,LT02,2,LT,Vidurio ir vakarų Lietuvos regionas,Vidurio ir vakarų Lietuvos regionas,0.0,NaN,0,LT02,"POLYGON ((25.82139 56.05218, 25.85250 56.02579..."